---
version: '3'
services:
  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    hostname: zipkin
    container_name: zipkin
    ports:
      - 9411:9411
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zk-1:2888:3888
  kafka:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    restart: always
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_SEGMENT_BYTES: 536870912
      KAFKA_LOG_RETENTION_BYTES: 536870912
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka:29092"
  kafkadrop3:
    image: obsidiandynamics/kafdrop
    restart: always
    hostname: kafkadrop
    container_name: kafkadrop
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    restart: always
    hostname: schema-registry
    container_name: schema-registry
    ports:
      - "9081:9081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:9081
    depends_on:
      - zookeeper
      - kafka
  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:5.3.1
    restart: always
    hostname: rest-proxy
    container_name: rest-proxy
    ports:
      - "8888:8888"
    environment:
      # KAFKA_REST_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8888/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:9081/
      KAFKA_REST_HOST_NAME: kafka-controller-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
    depends_on:
      - zookeeper
      - kafka
      - kafka-schema-registry
  control-center:
    image: confluentinc/cp-enterprise-control-center:5.3.1
    restart: always
    hostname: control-center
    container_name: control-center
#    networks:
#      - confluent
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:29092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 4
      CONTROL_CENTER_REPLICATION_FACTOR: 1
#      CONTROL_CENTER_CONNECT_CLUSTER: "connect:8083"
#      CONTROL_CENTER_KSQL_URL: "http://ksqldb-server:8088"
#      CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://0.0.0.0:9081"
      CONTROL_CENTER_UI_AUTOUPDATE_ENABLE: "false"
